In [1]:
from PISFA import PISFPA, PISFPA_PCA
import numpy as np
from tensorflow import keras
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
x_train = x_train.reshape((x_train.shape[0], 28 * 28))

In [4]:
b = np.zeros((y_train.size, y_train.max()+1))
b[np.arange(y_train.size), y_train] = 1

In [5]:
y_train = b

In [6]:
model = PISFPA(784, 200, 10)

Bias shape: (200,)
W shape: (784, 200)
Beta shape (200, 10)


In [7]:
model.fit(x_train, y_train, itrs=600, lam=1e-1)

C:\Users\ideapad 330\Desktop\EML\PISFPA\PISFA.py:13: RuntimeWarning: overflow encountered in exp
  return 1. / (1. + np.exp(-x))


In [8]:
predict = model(x_test.reshape((x_test.shape[0], 28 * 28)))

In [9]:
predict = np.argmax(predict, axis=1)

In [10]:
predict

array([7, 0, 1, ..., 4, 5, 6], dtype=int64)

In [11]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [12]:
sum(predict == y_test)/y_test.shape[0]

0.8342

### PCA

In [13]:
model = PISFPA_PCA(784, 200, 10)

In [14]:
model.fit(x_train, y_train, itrs=600, lam=1e-1)

C:\Users\ideapad 330\Desktop\EML\PISFPA\PISFA.py:13: RuntimeWarning: overflow encountered in exp
  return 1. / (1. + np.exp(-x))


In [15]:
predict = model(x_test.reshape((x_test.shape[0], 28 * 28)))

C:\Users\ideapad 330\Desktop\EML\PISFPA\PISFA.py:13: RuntimeWarning: overflow encountered in exp
  return 1. / (1. + np.exp(-x))


In [16]:
predict = np.argmax(predict, axis=1)

In [17]:
predict

array([7, 2, 1, ..., 9, 5, 6], dtype=int64)

In [18]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [19]:
sum(predict == y_test)/y_test.shape[0]

0.7624